server:
  port: 2021

# OracleDB connection settings
spring:
  jpa:
    hibernate:
      ddl-auto: update
  # Settings for the oracle connection
  datasource:
    url:
      jdbc:oracle:thin:@localhost:1521:xe
    username:
      system
    password:
      12345
    driver-class-oracle:
      jdbc:
        driver:
          OracleDriver
  application:
    name: ORDER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost